# Generated by Django 3.1.7 on 2021-04-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('sold_out', models.BooleanField(default=False)),
                ('likes', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('photos', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
